=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::AccountSettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountSettingsApi' do
  before do
    # run before each test
    @api_instance = Late::AccountSettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountSettingsApi' do
    it 'should create an instance of AccountSettingsApi' do
      expect(@api_instance).to be_instance_of(Late::AccountSettingsApi)
    end
  end

  # unit tests for delete_instagram_ice_breakers
  # Delete Instagram ice breakers
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_instagram_ice_breakers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_messenger_menu
  # Delete Facebook persistent menu
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_messenger_menu test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_telegram_commands
  # Delete Telegram bot commands
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_telegram_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_instagram_ice_breakers
  # Get Instagram ice breakers
  # Get the ice breaker configuration for an Instagram account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetMessengerMenu200Response]
  describe 'get_instagram_ice_breakers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_messenger_menu
  # Get Facebook persistent menu
  # Get the persistent menu configuration for a Facebook Messenger account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetMessengerMenu200Response]
  describe 'get_messenger_menu test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_telegram_commands
  # Get Telegram bot commands
  # Get the bot commands configuration for a Telegram account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetTelegramCommands200Response]
  describe 'get_telegram_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_instagram_ice_breakers
  # Set Instagram ice breakers
  # Set ice breakers for an Instagram account. Max 4 ice breakers, question max 80 chars.
  # @param account_id 
  # @param set_instagram_ice_breakers_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set_instagram_ice_breakers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_messenger_menu
  # Set Facebook persistent menu
  # Set the persistent menu for a Facebook Messenger account. Max 3 top-level items, max 5 nested items.
  # @param account_id 
  # @param set_messenger_menu_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set_messenger_menu test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_telegram_commands
  # Set Telegram bot commands
  # Set bot commands for a Telegram account.
  # @param account_id 
  # @param set_telegram_commands_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set_telegram_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
