=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::AnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalyticsApi' do
  before do
    # run before each test
    @api_instance = Late::AnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyticsApi' do
    it 'should create an instance of AnalyticsApi' do
      expect(@api_instance).to be_instance_of(Late::AnalyticsApi)
    end
  end

  # unit tests for get_analytics
  # Get post analytics
  # Returns analytics for posts. With postId, returns a single post. Without it, returns a paginated list with overview stats. This endpoint returns External Post IDs by default. The postId parameter accepts both Late Post IDs and External Post IDs, auto-resolving Late IDs to External Post analytics. Use latePostId in responses to link back to your original post, or platformPostUrl as a stable identifier. isExternal indicates post origin (true &#x3D; synced from platform). For follower stats, use /v1/accounts/follower-stats. LinkedIn personal accounts: per-post analytics only for Late-published posts. Telegram: not available. Data is cached and refreshed at most once per hour. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :post_id Returns analytics for a single post. Accepts both Late Post IDs and External Post IDs. Late IDs are auto-resolved to External Post analytics.
  # @option opts [String] :platform Filter by platform (default \&quot;all\&quot;)
  # @option opts [String] :profile_id Filter by profile ID (default \&quot;all\&quot;)
  # @option opts [String] :source Filter by post source: late (posted via Late API), external (synced from platform), all (default)
  # @option opts [Date] :from_date Inclusive lower bound
  # @option opts [Date] :to_date Inclusive upper bound
  # @option opts [Integer] :limit Page size (default 50)
  # @option opts [Integer] :page Page number (default 1)
  # @option opts [String] :sort_by Sort by date or engagement
  # @option opts [String] :order Sort order
  # @return [GetAnalytics200Response]
  describe 'get_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_follower_stats
  # Get follower stats
  # Returns follower count history and growth metrics for connected social accounts. Requires analytics add-on subscription. Follower counts are refreshed once per day. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_ids Comma-separated list of account IDs (optional, defaults to all user&#39;s accounts)
  # @option opts [String] :profile_id Filter by profile ID
  # @option opts [Date] :from_date Start date in YYYY-MM-DD format (defaults to 30 days ago)
  # @option opts [Date] :to_date End date in YYYY-MM-DD format (defaults to today)
  # @option opts [String] :granularity Data aggregation level
  # @return [GetFollowerStats200Response]
  describe 'get_follower_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_aggregate_analytics
  # Get LinkedIn aggregate stats
  # Returns aggregate analytics across all posts for a LinkedIn personal account. Org accounts should use /v1/analytics instead. Required scope: r_member_postAnalytics (missing scope returns 403). Aggregation: TOTAL (default, lifetime totals) or DAILY (time series). Use startDate/endDate to filter. MEMBERS_REACHED is not available with DAILY aggregation. 
  # @param account_id The ID of the LinkedIn personal account
  # @param [Hash] opts the optional parameters
  # @option opts [String] :aggregation Type of aggregation: TOTAL (default, returns single totals) or DAILY (returns daily breakdown). Note: MEMBERS_REACHED is not available with DAILY aggregation. 
  # @option opts [Date] :start_date Start date for analytics data in YYYY-MM-DD format. If provided without endDate, endDate defaults to today. If omitted entirely, returns lifetime analytics. 
  # @option opts [Date] :end_date End date for analytics data in YYYY-MM-DD format (exclusive). If provided without startDate, startDate defaults to 30 days before endDate. 
  # @option opts [String] :metrics Comma-separated list of metrics to fetch. If omitted, fetches all available metrics. Valid values: IMPRESSION, MEMBERS_REACHED, REACTION, COMMENT, RESHARE 
  # @return [GetLinkedInAggregateAnalytics200Response]
  describe 'get_linked_in_aggregate_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_post_analytics
  # Get LinkedIn post stats
  # Returns analytics for a specific LinkedIn post using its URN. Works for both personal and organization accounts. Useful for fetching analytics of posts not published through Late. Personal accounts require r_member_postAnalytics scope and return impressions, reach, likes, comments, shares, and video views (clicks not available). Organization accounts require r_organization_social scope and additionally return clicks and engagement rate. 
  # @param account_id The ID of the LinkedIn account
  # @param urn The LinkedIn post URN
  # @param [Hash] opts the optional parameters
  # @return [GetLinkedInPostAnalytics200Response]
  describe 'get_linked_in_post_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_you_tube_daily_views
  # Get YouTube daily views
  # Returns historical daily view counts for a specific YouTube video. Uses YouTube Analytics API v2 to fetch daily breakdowns including views, watch time, and subscriber changes.  Requires the yt-analytics.readonly OAuth scope. Existing YouTube accounts may need to re-authorize. If the scope is missing, the response includes a reauthorizeUrl. Data has a 2-3 day delay; endDate is automatically capped to 3 days ago. Maximum 90 days of historical data. Defaults to last 30 days. 
  # @param video_id The YouTube video ID (e.g., \&quot;dQw4w9WgXcQ\&quot;)
  # @param account_id The Late account ID for the YouTube account
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :start_date Start date (YYYY-MM-DD). Defaults to 30 days ago.
  # @option opts [Date] :end_date End date (YYYY-MM-DD). Defaults to 3 days ago (YouTube data latency).
  # @return [YouTubeDailyViewsResponse]
  describe 'get_you_tube_daily_views test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
