=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::AnalyticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AnalyticsApi' do
  before do
    # run before each test
    @api_instance = Late::AnalyticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnalyticsApi' do
    it 'should create an instance of AnalyticsApi' do
      expect(@api_instance).to be_instance_of(Late::AnalyticsApi)
    end
  end

  # unit tests for get_analytics
  # Get post analytics
  # Returns analytics for posts. With &#x60;postId&#x60;, returns a single post&#39;s analytics. Without it, returns a paginated list with overview stats.  **Post ID types:** This endpoint returns External Post IDs by default. The &#x60;postId&#x60; parameter accepts both Late Post IDs (from &#x60;POST /v1/posts&#x60;) and External Post IDs. Late Post IDs are automatically resolved to External Post analytics. Use &#x60;latePostId&#x60; in responses to link analytics back to your original Late post, or &#x60;platformPostUrl&#x60; as a stable identifier.  **List response:** Use &#x60;isExternal&#x60; to identify post origin. &#x60;isExternal: true&#x60; means synced from platform, &#x60;isExternal: false&#x60; means queried by Late post ID.  For follower stats, use &#x60;/v1/accounts/follower-stats&#x60; instead.  **Platform notes:** - LinkedIn personal accounts: per-post analytics only for posts published through Late (API restriction). - Telegram: analytics not available (Bot API limitation).  **Data freshness:** Cached and refreshed at most once per hour. Stale caches trigger a background refresh. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :post_id Returns analytics for a single post. Accepts both Late Post IDs (from &#x60;POST /v1/posts&#x60;)  and External Post IDs (from this endpoint&#39;s list response). The API automatically  resolves Late Post IDs to their corresponding External Post analytics. 
  # @option opts [String] :platform Filter by platform (default \&quot;all\&quot;)
  # @option opts [String] :profile_id Filter by profile ID (default \&quot;all\&quot;)
  # @option opts [String] :source Filter by post source: - &#x60;late&#x60; - Only posts scheduled/published via Late API - &#x60;external&#x60; - Only posts synced from the platform (not posted via Late) - &#x60;all&#x60; - All posts (default) 
  # @option opts [Date] :from_date Inclusive lower bound
  # @option opts [Date] :to_date Inclusive upper bound
  # @option opts [Integer] :limit Page size (default 50)
  # @option opts [Integer] :page Page number (default 1)
  # @option opts [String] :sort_by Sort by date or engagement
  # @option opts [String] :order Sort order
  # @return [GetAnalytics200Response]
  describe 'get_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_follower_stats
  # Get follower stats
  # Returns follower count history and growth metrics for connected social accounts. **Requires analytics add-on subscription.**  **Data Freshness:** Follower counts are automatically refreshed once per day. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_ids Comma-separated list of account IDs (optional, defaults to all user&#39;s accounts)
  # @option opts [String] :profile_id Filter by profile ID
  # @option opts [Date] :from_date Start date in YYYY-MM-DD format (defaults to 30 days ago)
  # @option opts [Date] :to_date End date in YYYY-MM-DD format (defaults to today)
  # @option opts [String] :granularity Data aggregation level
  # @return [GetFollowerStats200Response]
  describe 'get_follower_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_aggregate_analytics
  # Get LinkedIn aggregate stats
  # Returns aggregate analytics across all posts for a LinkedIn personal account. Organization accounts should use &#x60;/v1/analytics&#x60; instead.  **Required scope:** &#x60;r_member_postAnalytics&#x60;. Missing scope returns 403 with reconnect instructions.  **Aggregation:** &#x60;TOTAL&#x60; (default, lifetime totals) or &#x60;DAILY&#x60; (time series). Use &#x60;startDate&#x60;/&#x60;endDate&#x60; to filter by date range. Note: &#x60;MEMBERS_REACHED&#x60; is not available with &#x60;DAILY&#x60; aggregation. 
  # @param account_id The ID of the LinkedIn personal account
  # @param [Hash] opts the optional parameters
  # @option opts [String] :aggregation Type of aggregation for the analytics data. - &#x60;TOTAL&#x60; (default): Returns single totals for each metric - &#x60;DAILY&#x60;: Returns daily breakdown of metrics  Note: &#x60;MEMBERS_REACHED&#x60; metric is not available with &#x60;DAILY&#x60; aggregation. 
  # @option opts [Date] :start_date Start date for analytics data in YYYY-MM-DD format. If provided without endDate, endDate defaults to today. If omitted entirely, returns lifetime analytics. 
  # @option opts [Date] :end_date End date for analytics data in YYYY-MM-DD format (exclusive). If provided without startDate, startDate defaults to 30 days before endDate. 
  # @option opts [String] :metrics Comma-separated list of metrics to fetch. If omitted, fetches all available metrics. Valid values: IMPRESSION, MEMBERS_REACHED, REACTION, COMMENT, RESHARE 
  # @return [GetLinkedInAggregateAnalytics200Response]
  describe 'get_linked_in_aggregate_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_post_analytics
  # Get LinkedIn post stats
  # Returns analytics for a specific LinkedIn post using its URN. Works for both personal and organization accounts.  This is useful for fetching analytics of posts that weren&#39;t published through Late, as long as you have the post URN.  **For Personal Accounts:** - Uses &#x60;memberCreatorPostAnalytics&#x60; API + &#x60;memberCreatorVideoAnalytics&#x60; for video posts - Requires &#x60;r_member_postAnalytics&#x60; scope - Available metrics: impressions, reach, likes, comments, shares, video views (video posts only) - **Clicks are NOT available** for personal accounts  **For Organization Accounts:** - Uses &#x60;organizationalEntityShareStatistics&#x60; API + &#x60;videoAnalytics&#x60; for video posts - Requires &#x60;r_organization_social&#x60; scope - Available metrics: impressions, reach, clicks, likes, comments, shares, video views (video posts only), engagement rate 
  # @param account_id The ID of the LinkedIn account
  # @param urn The LinkedIn post URN
  # @param [Hash] opts the optional parameters
  # @return [GetLinkedInPostAnalytics200Response]
  describe 'get_linked_in_post_analytics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_you_tube_daily_views
  # Get YouTube daily views
  # Returns historical daily view counts for a specific YouTube video. Uses YouTube Analytics API v2 to fetch daily breakdowns including views, watch time, and subscriber changes.  **Required Scope:** This endpoint requires the &#x60;yt-analytics.readonly&#x60; OAuth scope. Existing YouTube accounts may need to re-authorize to grant this permission. If the scope is missing, the response will include a &#x60;reauthorizeUrl&#x60;.  **Data Latency:** YouTube Analytics data has a 2-3 day delay. The &#x60;endDate&#x60; is automatically capped to 3 days ago.  **Date Range:** Maximum 90 days of historical data available. Defaults to last 30 days. 
  # @param video_id The YouTube video ID (e.g., \&quot;dQw4w9WgXcQ\&quot;)
  # @param account_id The Late account ID for the YouTube account
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :start_date Start date (YYYY-MM-DD). Defaults to 30 days ago.
  # @option opts [Date] :end_date End date (YYYY-MM-DD). Defaults to 3 days ago (YouTube data latency).
  # @return [YouTubeDailyViewsResponse]
  describe 'get_you_tube_daily_views test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
