=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::ConnectApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConnectApi' do
  before do
    # run before each test
    @api_instance = Late::ConnectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConnectApi' do
    it 'should create an instance of ConnectApi' do
      expect(@api_instance).to be_instance_of(Late::ConnectApi)
    end
  end

  # unit tests for complete_telegram_connect
  # Check Telegram status
  # Poll this endpoint to check if a Telegram access code has been used to connect a channel/group.  **Recommended polling interval:** 3 seconds  **Status values:** - &#x60;pending&#x60;: Code is valid, waiting for user to complete connection - &#x60;connected&#x60;: Connection successful - channel/group is now linked - &#x60;expired&#x60;: Code has expired, generate a new one 
  # @param code The access code to check status for
  # @param [Hash] opts the optional parameters
  # @return [CompleteTelegramConnect200Response]
  describe 'complete_telegram_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for connect_bluesky_credentials
  # Connect Bluesky account
  # Connect a Bluesky account using identifier (handle or email) and an app password.  To get your userId for the state parameter, call &#x60;GET /v1/users&#x60; - the response includes a &#x60;currentUserId&#x60; field. 
  # @param connect_bluesky_credentials_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'connect_bluesky_credentials test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_connect_url
  # Get OAuth connect URL
  # Initiate an OAuth connection flow for any supported social media platform.  **Standard Flow (Hosted UI):** 1. Call this endpoint with your API key and &#x60;redirect_url&#x60; (optional) 2. Redirect your user to the returned &#x60;authUrl&#x60; 3. After OAuth, Late hosts the page/account selection UI 4. Once the user picks, Late saves the connection and redirects to your &#x60;redirect_url&#x60; (if provided)  **Headless Mode (Facebook, LinkedIn, Pinterest, Google Business, Snapchat):** Build your own branded selection UI while Late handles OAuth. Add &#x60;&amp;headless&#x3D;true&#x60; to this endpoint:  &#x60;GET /v1/connect/{platform}?profileId&#x3D;PROFILE_ID&amp;redirect_url&#x3D;https://yourapp.com/callback&amp;headless&#x3D;true&#x60;  After OAuth, the user is redirected to your &#x60;redirect_url&#x60; with OAuth data including &#x60;profileId&#x60;, &#x60;tempToken&#x60;, &#x60;userProfile&#x60;, &#x60;connect_token&#x60;, &#x60;platform&#x60;, and a &#x60;step&#x60; parameter indicating what selection is needed.  **Facebook example:** 1. Redirect params include &#x60;step&#x3D;select_page&#x60; 2. Use &#x60;GET /v1/connect/facebook/select-page&#x60; to fetch pages 3. Use &#x60;POST /v1/connect/facebook/select-page&#x60; to save the selected page  LinkedIn, Pinterest, Google Business, and Snapchat follow the same pattern with their respective selection endpoints. LinkedIn uses &#x60;pendingDataToken&#x60; instead of &#x60;tempToken&#x60; in redirect params; call &#x60;GET /v1/connect/pending-data?token&#x3D;TOKEN&#x60; to retrieve the OAuth data (one-time use, expires in 10 minutes). 
  # @param platform Social media platform to connect
  # @param profile_id Your Late profile ID (get from /v1/profiles)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :redirect_url Your custom redirect URL after connection completes.  **Standard Mode:** After the user selects an account, Late redirects here with &#x60;?connected&#x3D;{platform}&amp;profileId&#x3D;X&amp;username&#x3D;Y&#x60;.  **Headless Mode:** Pass &#x60;headless&#x3D;true&#x60; as a query parameter on this endpoint. After OAuth, the user is redirected to your URL with OAuth data (&#x60;profileId&#x60;, &#x60;tempToken&#x60;, &#x60;userProfile&#x60;, &#x60;connect_token&#x60;, &#x60;platform&#x60;, &#x60;step&#x60;). See the main endpoint description for details.  Example: &#x60;https://yourdomain.com/integrations/callback&#x60; 
  # @return [GetConnectUrl200Response]
  describe 'get_connect_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_facebook_pages
  # List Facebook pages
  # Returns all Facebook pages the connected account has access to, including the currently selected page.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetFacebookPages200Response]
  describe 'get_facebook_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gmb_locations
  # List Google Business locations
  # Returns all Google Business Profile locations the connected account has access to, including the currently selected location.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetGmbLocations200Response]
  describe 'get_gmb_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_organizations
  # List LinkedIn orgs
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetLinkedInOrganizations200Response]
  describe 'get_linked_in_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pending_o_auth_data
  # Get pending OAuth data
  # **Fetch Pending OAuth Data for Headless Mode**  In headless mode, platforms like LinkedIn store OAuth selection data (organizations, pages, etc.) in the database instead of passing it via URL parameters. This prevents URI_TOO_LONG errors when users have many organizations/pages to select from.  After OAuth redirect, use the &#x60;pendingDataToken&#x60; from the URL to fetch the stored data.  **Important:** - This endpoint is one-time use: data is deleted after being fetched - Data expires automatically after 10 minutes if not fetched - No authentication required, just the token from the redirect URL 
  # @param token The pending data token from the OAuth redirect URL (&#x60;pendingDataToken&#x60; parameter)
  # @param [Hash] opts the optional parameters
  # @return [GetPendingOAuthData200Response]
  describe 'get_pending_o_auth_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pinterest_boards
  # List Pinterest boards
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetPinterestBoards200Response]
  describe 'get_pinterest_boards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_reddit_flairs
  # List subreddit flairs
  # @param account_id 
  # @param subreddit Subreddit name (without \&quot;r/\&quot; prefix) to fetch flairs for
  # @param [Hash] opts the optional parameters
  # @return [GetRedditFlairs200Response]
  describe 'get_reddit_flairs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_reddit_subreddits
  # List Reddit subreddits
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRedditSubreddits200Response]
  describe 'get_reddit_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_telegram_connect_status
  # Generate Telegram code
  # Generate a unique access code for connecting a Telegram channel or group.  **Connection Flow:** 1. Call this endpoint to get an access code (valid for 15 minutes) 2. Add the bot (@LateScheduleBot or your configured bot) as an administrator in your Telegram channel/group 3. Open a private chat with the bot 4. Send: &#x60;{CODE} @yourchannel&#x60; (e.g., &#x60;LATE-ABC123 @mychannel&#x60;) 5. Poll &#x60;PATCH /v1/connect/telegram?code&#x3D;{CODE}&#x60; to check connection status  **Alternative for private channels:** If your channel has no public username, forward any message from the channel to the bot along with the access code. 
  # @param profile_id The profile ID to connect the Telegram account to
  # @param [Hash] opts the optional parameters
  # @return [GetTelegramConnectStatus200Response]
  describe 'get_telegram_connect_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for handle_o_auth_callback
  # Complete OAuth callback
  # @param platform 
  # @param handle_o_auth_callback_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'handle_o_auth_callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for initiate_telegram_connect
  # Connect Telegram directly
  # Connect a Telegram channel/group directly using the chat ID.  This is an alternative to the access code flow for power users who know their Telegram chat ID. The bot must already be added as an administrator in the channel/group. 
  # @param initiate_telegram_connect_request 
  # @param [Hash] opts the optional parameters
  # @return [InitiateTelegramConnect200Response]
  describe 'initiate_telegram_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_facebook_pages
  # List Facebook pages
  # **Headless Mode for Custom UI**  After initiating Facebook OAuth via &#x60;/v1/connect/facebook&#x60;, you&#39;ll be redirected to  &#x60;/connect/facebook/select-page&#x60; with query params including &#x60;tempToken&#x60; and &#x60;userProfile&#x60;.  For a **headless/whitelabeled flow**, extract these params from the URL and call this  endpoint to retrieve the list of Facebook Pages the user can manage. Then build your  own UI to let users select a page.  **Note:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key  (rather than a browser session). 
  # @param profile_id Profile ID from your connection flow
  # @param temp_token Temporary Facebook access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListFacebookPages200Response]
  describe 'list_facebook_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_google_business_locations
  # List Google Business locations
  # **Headless Mode for Custom UI**  After initiating Google Business OAuth via &#x60;/v1/connect/googlebusiness?headless&#x3D;true&#x60;, you&#39;ll be redirected  to your &#x60;redirect_url&#x60; with query params including &#x60;tempToken&#x60; and &#x60;userProfile&#x60;.  For a **headless/whitelabeled flow**, extract these params from the URL and call this  endpoint to retrieve the list of Google Business locations the user can manage. Then build your  own UI to let users select a location.  **Note:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key  (rather than a browser session). 
  # @param profile_id Profile ID from your connection flow
  # @param temp_token Temporary Google access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListGoogleBusinessLocations200Response]
  describe 'list_google_business_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_linked_in_organizations
  # List LinkedIn orgs
  # **Fetch Full Organization Details for Custom UI**  After LinkedIn OAuth in headless mode, the redirect URL contains organization data with only &#x60;id&#x60;, &#x60;urn&#x60;, and &#x60;name&#x60; fields (additional details are excluded to prevent URL length issues with many organizations).  Use this endpoint to fetch full organization details including logos, vanity names, websites, and more if you want to display them in your custom selection UI.  **Note:** This endpoint requires no authentication - just the &#x60;tempToken&#x60; from the OAuth redirect. Details are fetched directly from LinkedIn&#39;s API in parallel for fast response times. 
  # @param temp_token The temporary LinkedIn access token from the OAuth redirect
  # @param org_ids Comma-separated list of organization IDs to fetch details for (max 100)
  # @param [Hash] opts the optional parameters
  # @return [ListLinkedInOrganizations200Response]
  describe 'list_linked_in_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pinterest_boards_for_selection
  # List Pinterest boards
  # **Retrieve Pinterest Boards for Selection UI**  After initiating Pinterest OAuth via &#x60;/v1/connect/pinterest&#x60; with &#x60;headless&#x3D;true&#x60;, you&#39;ll be redirected to your &#x60;redirect_url&#x60; with query params including &#x60;tempToken&#x60; and &#x60;userProfile&#x60;.  If you want to build your own fully-branded board selector (instead of Late&#39;s hosted UI), call this endpoint to retrieve the list of Pinterest Boards the user can post to. Then build your UI and call &#x60;POST /v1/connect/pinterest/select-board&#x60; to save the selection.  **Authentication:** Use &#x60;X-Connect-Token&#x60; header with the &#x60;connect_token&#x60; from the redirect URL. 
  # @param x_connect_token Short-lived connect token from the OAuth redirect
  # @param profile_id Your Late profile ID
  # @param temp_token Temporary Pinterest access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListPinterestBoardsForSelection200Response]
  describe 'list_pinterest_boards_for_selection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_snapchat_profiles
  # List Snapchat profiles
  # **Headless Mode for Custom UI**  After initiating Snapchat OAuth via &#x60;/v1/connect/snapchat?headless&#x3D;true&#x60;, you&#39;ll be redirected to your &#x60;redirect_url&#x60; with query params including &#x60;tempToken&#x60;, &#x60;userProfile&#x60;, and &#x60;publicProfiles&#x60;.  If you want to build your own fully-branded profile selector (instead of Late&#39;s hosted UI), call this endpoint to retrieve the list of Snapchat Public Profiles the user can post to. Then build your UI and call &#x60;POST /v1/connect/snapchat/select-profile&#x60; to save the selection.  **Authentication:** Use &#x60;X-Connect-Token&#x60; header with the &#x60;connect_token&#x60; from the redirect URL. 
  # @param x_connect_token Short-lived connect token from the OAuth redirect
  # @param profile_id Your Late profile ID
  # @param temp_token Temporary Snapchat access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListSnapchatProfiles200Response]
  describe 'list_snapchat_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_facebook_page
  # Select Facebook page
  # **Complete the Headless Flow**  After displaying your custom UI with the list of pages from the GET endpoint, call this  endpoint to finalize the connection with the user&#39;s selected page.  The &#x60;userProfile&#x60; should be the decoded JSON object from the &#x60;userProfile&#x60; query param  in the OAuth callback redirect URL.  **Note:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key. 
  # @param select_facebook_page_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectFacebookPage200Response]
  describe 'select_facebook_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_google_business_location
  # Select Google Business location
  # **Complete the Headless Flow**  After displaying your custom UI with the list of locations from the GET &#x60;/v1/connect/googlebusiness/locations&#x60;  endpoint, call this endpoint to finalize the connection with the user&#39;s selected location.  The &#x60;userProfile&#x60; should be the decoded JSON object from the &#x60;userProfile&#x60; query param  in the OAuth callback redirect URL. It contains important token information (including refresh token).  **Note:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key. 
  # @param select_google_business_location_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectGoogleBusinessLocation200Response]
  describe 'select_google_business_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_linked_in_organization
  # Select LinkedIn org
  # **Complete the LinkedIn Connection Flow**  After OAuth, the user is redirected with &#x60;organizations&#x60; in the URL params (if they have org admin access). The organizations array contains &#x60;id&#x60;, &#x60;urn&#x60;, and &#x60;name&#x60; fields. Use this data to build your UI,  then call this endpoint to save the selection.  Set &#x60;accountType&#x60; to &#x60;personal&#x60; to connect as the user&#39;s personal LinkedIn profile, or &#x60;organization&#x60; to connect as a company page (requires &#x60;selectedOrganization&#x60; object).  **Personal Profile:** To connect a personal LinkedIn account, set &#x60;accountType&#x60; to &#x60;\&quot;personal\&quot;&#x60; and **omit** the &#x60;selectedOrganization&#x60; field entirely. This is the simplest flow.  **Headless Mode:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key. 
  # @param select_linked_in_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectLinkedInOrganization200Response]
  describe 'select_linked_in_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_pinterest_board
  # Select Pinterest board
  # **Complete the Pinterest Connection Flow**  After OAuth, use this endpoint to save the selected board and complete the Pinterest account connection.  **Headless Mode:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key. 
  # @param select_pinterest_board_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectPinterestBoard200Response]
  describe 'select_pinterest_board test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_snapchat_profile
  # Select Snapchat profile
  # **Complete the Snapchat Connection Flow**  After OAuth, use this endpoint to save the selected Public Profile and complete the Snapchat account connection. Snapchat requires a Public Profile to publish Stories, Saved Stories, and Spotlight content.  **Headless Mode:** Use the &#x60;X-Connect-Token&#x60; header if you initiated the connection via API key.  After initiating Snapchat OAuth via &#x60;/v1/connect/snapchat?headless&#x3D;true&#x60;, you&#39;ll be redirected to your &#x60;redirect_url&#x60; with query params including: - &#x60;tempToken&#x60; - Temporary access token - &#x60;userProfile&#x60; - URL-encoded JSON with user info - &#x60;publicProfiles&#x60; - URL-encoded JSON array of available public profiles - &#x60;connect_token&#x60; - Short-lived token for API authentication - &#x60;platform&#x3D;snapchat&#x60; - &#x60;step&#x3D;select_public_profile&#x60;  Parse &#x60;publicProfiles&#x60; to build your custom selector UI, then call this endpoint with the selected profile. 
  # @param select_snapchat_profile_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_connect_token Short-lived connect token from the OAuth redirect (for API users)
  # @return [SelectSnapchatProfile200Response]
  describe 'select_snapchat_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_facebook_page
  # Update Facebook page
  # @param account_id 
  # @param update_facebook_page_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateFacebookPage200Response]
  describe 'update_facebook_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_gmb_location
  # Update Google Business location
  # @param account_id 
  # @param update_gmb_location_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateGmbLocation200Response]
  describe 'update_gmb_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_linked_in_organization
  # Switch LinkedIn account type
  # @param account_id 
  # @param update_linked_in_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'update_linked_in_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_pinterest_boards
  # Set default Pinterest board
  # @param account_id 
  # @param update_pinterest_boards_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'update_pinterest_boards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_reddit_subreddits
  # Set default subreddit
  # @param account_id 
  # @param update_reddit_subreddits_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateRedditSubreddits200Response]
  describe 'update_reddit_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
