=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::ConnectApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConnectApi' do
  before do
    # run before each test
    @api_instance = Late::ConnectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConnectApi' do
    it 'should create an instance of ConnectApi' do
      expect(@api_instance).to be_instance_of(Late::ConnectApi)
    end
  end

  # unit tests for complete_telegram_connect
  # Check Telegram status
  # Poll this endpoint to check if a Telegram access code has been used to connect a channel/group. Recommended polling interval: 3 seconds. Status values: pending (waiting for user), connected (channel/group linked), expired (generate a new code). 
  # @param code The access code to check status for
  # @param [Hash] opts the optional parameters
  # @return [CompleteTelegramConnect200Response]
  describe 'complete_telegram_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for connect_bluesky_credentials
  # Connect Bluesky account
  # Connect a Bluesky account using identifier (handle or email) and an app password. To get your userId for the state parameter, call GET /v1/users which includes a currentUserId field. 
  # @param connect_bluesky_credentials_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'connect_bluesky_credentials test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_connect_url
  # Get OAuth connect URL
  # Initiate an OAuth connection flow for any supported platform. Standard flow: call this endpoint, redirect user to the returned authUrl, Late hosts the selection UI, then redirects to your redirect_url. Headless mode (Facebook, LinkedIn, Pinterest, Google Business, Snapchat): add headless&#x3D;true to this endpoint. After OAuth, the user is redirected to your redirect_url with OAuth data (profileId, tempToken, userProfile, connect_token, platform, step). Use the platform-specific selection endpoints to fetch options and save the selection. LinkedIn uses pendingDataToken instead of tempToken; call GET /v1/connect/pending-data?token&#x3D;TOKEN to retrieve OAuth data (one-time use, expires in 10 minutes). 
  # @param platform Social media platform to connect
  # @param profile_id Your Late profile ID (get from /v1/profiles)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :redirect_url Your custom redirect URL after connection completes. Standard mode: Late redirects here with ?connected&#x3D;{platform}&amp;profileId&#x3D;X&amp;username&#x3D;Y. Headless mode: pass headless&#x3D;true on this endpoint. User is redirected to your URL with OAuth data (profileId, tempToken, userProfile, connect_token, platform, step). See endpoint description for details. 
  # @return [GetConnectUrl200Response]
  describe 'get_connect_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_facebook_pages
  # List Facebook pages
  # Returns all Facebook pages the connected account has access to, including the currently selected page.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetFacebookPages200Response]
  describe 'get_facebook_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_gmb_locations
  # List GBP locations
  # Returns all Google Business Profile locations the connected account has access to, including the currently selected location.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetGmbLocations200Response]
  describe 'get_gmb_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_linked_in_organizations
  # List LinkedIn orgs
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetLinkedInOrganizations200Response]
  describe 'get_linked_in_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pending_o_auth_data
  # Get pending OAuth data
  # Fetch pending OAuth data for headless mode. Platforms like LinkedIn store OAuth selection data (organizations, pages, etc.) server-side to prevent URI_TOO_LONG errors. After OAuth redirect, use the pendingDataToken from the URL to fetch the stored data. This endpoint is one-time use (data is deleted after fetch) and expires after 10 minutes. No authentication required, just the token. 
  # @param token The pending data token from the OAuth redirect URL (pendingDataToken parameter)
  # @param [Hash] opts the optional parameters
  # @return [GetPendingOAuthData200Response]
  describe 'get_pending_o_auth_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pinterest_boards
  # List Pinterest boards
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetPinterestBoards200Response]
  describe 'get_pinterest_boards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_reddit_flairs
  # List subreddit flairs
  # @param account_id 
  # @param subreddit Subreddit name (without \&quot;r/\&quot; prefix) to fetch flairs for
  # @param [Hash] opts the optional parameters
  # @return [GetRedditFlairs200Response]
  describe 'get_reddit_flairs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_reddit_subreddits
  # List Reddit subreddits
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRedditSubreddits200Response]
  describe 'get_reddit_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_telegram_connect_status
  # Generate Telegram code
  # Generate a unique access code for connecting a Telegram channel or group. Flow: get an access code (valid 15 minutes), add the bot as admin in your channel/group, open a private chat with the bot, send the code + @yourchannel (e.g. LATE-ABC123 @mychannel), then poll PATCH /v1/connect/telegram?code&#x3D;{CODE} to check connection status. For private channels without a public username, forward any message from the channel to the bot along with the access code. 
  # @param profile_id The profile ID to connect the Telegram account to
  # @param [Hash] opts the optional parameters
  # @return [GetTelegramConnectStatus200Response]
  describe 'get_telegram_connect_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for handle_o_auth_callback
  # Complete OAuth callback
  # @param platform 
  # @param handle_o_auth_callback_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'handle_o_auth_callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for initiate_telegram_connect
  # Connect Telegram directly
  # Connect a Telegram channel/group directly using the chat ID.  This is an alternative to the access code flow for power users who know their Telegram chat ID. The bot must already be added as an administrator in the channel/group. 
  # @param initiate_telegram_connect_request 
  # @param [Hash] opts the optional parameters
  # @return [InitiateTelegramConnect200Response]
  describe 'initiate_telegram_connect test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_facebook_pages
  # List Facebook pages
  # Returns the list of Facebook Pages the user can manage after OAuth. Extract tempToken and userProfile from the OAuth redirect params and pass them here. Use the X-Connect-Token header if connecting via API key.
  # @param profile_id Profile ID from your connection flow
  # @param temp_token Temporary Facebook access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListFacebookPages200Response]
  describe 'list_facebook_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_google_business_locations
  # List GBP locations
  # For headless/whitelabel flows. After Google Business OAuth with headless&#x3D;true, you&#39;ll be redirected to your redirect_url with tempToken and userProfile params. Call this endpoint to retrieve the list of locations the user can manage, then build your own UI to let them select one. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param profile_id Profile ID from your connection flow
  # @param temp_token Temporary Google access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListGoogleBusinessLocations200Response]
  describe 'list_google_business_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_linked_in_organizations
  # List LinkedIn orgs
  # Fetch full organization details for custom UI. After LinkedIn OAuth in headless mode, the redirect URL only contains id, urn, and name fields. Use this endpoint to fetch full details including logos, vanity names, websites, and more. No authentication required, just the tempToken from the OAuth redirect. 
  # @param temp_token The temporary LinkedIn access token from the OAuth redirect
  # @param org_ids Comma-separated list of organization IDs to fetch details for (max 100)
  # @param [Hash] opts the optional parameters
  # @return [ListLinkedInOrganizations200Response]
  describe 'list_linked_in_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pinterest_boards_for_selection
  # List Pinterest boards
  # Retrieve Pinterest boards for headless selection UI. After Pinterest OAuth with headless&#x3D;true, you&#39;ll be redirected to your redirect_url with tempToken and userProfile params. Call this endpoint to retrieve the list of boards the user can post to, then build your UI and call POST /v1/connect/pinterest/select-board to save the selection. Use X-Connect-Token header with the connect_token from the redirect URL. 
  # @param x_connect_token Short-lived connect token from the OAuth redirect
  # @param profile_id Your Late profile ID
  # @param temp_token Temporary Pinterest access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListPinterestBoardsForSelection200Response]
  describe 'list_pinterest_boards_for_selection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_snapchat_profiles
  # List Snapchat profiles
  # For headless/whitelabel flows. After Snapchat OAuth with headless&#x3D;true, you&#39;ll be redirected to your redirect_url with tempToken, userProfile, and publicProfiles params. Call this endpoint to retrieve the list of Snapchat Public Profiles the user can post to, then build your UI and call POST /v1/connect/snapchat/select-profile to save the selection. Use X-Connect-Token header with the connect_token from the redirect URL. 
  # @param x_connect_token Short-lived connect token from the OAuth redirect
  # @param profile_id Your Late profile ID
  # @param temp_token Temporary Snapchat access token from the OAuth callback redirect
  # @param [Hash] opts the optional parameters
  # @return [ListSnapchatProfiles200Response]
  describe 'list_snapchat_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_facebook_page
  # Select Facebook page
  # Complete the headless flow. After displaying your custom UI with the list of pages from the GET endpoint, call this endpoint to finalize the connection with the user&#39;s selected page. The userProfile should be the decoded JSON object from the userProfile query param in the OAuth callback redirect URL. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param select_facebook_page_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectFacebookPage200Response]
  describe 'select_facebook_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_google_business_location
  # Select GBP location
  # Complete the headless flow. After displaying your custom UI with the list of locations from the GET /v1/connect/googlebusiness/locations endpoint, call this endpoint to finalize the connection with the user&#39;s selected location. The userProfile should be the decoded JSON object from the userProfile query param in the OAuth callback redirect URL. It contains important token information including the refresh token. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param select_google_business_location_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectGoogleBusinessLocation200Response]
  describe 'select_google_business_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_linked_in_organization
  # Select LinkedIn org
  # Complete the LinkedIn connection flow. After OAuth, the user is redirected with organizations in the URL params (if they have org admin access). Use this data to build your UI, then call this endpoint to save the selection. Set accountType to \&quot;personal\&quot; for a personal profile (omit selectedOrganization), or \&quot;organization\&quot; to connect as a company page. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param select_linked_in_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectLinkedInOrganization200Response]
  describe 'select_linked_in_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_pinterest_board
  # Select Pinterest board
  # Complete the Pinterest connection flow. After OAuth, use this endpoint to save the selected board and complete the account connection. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param select_pinterest_board_request 
  # @param [Hash] opts the optional parameters
  # @return [SelectPinterestBoard200Response]
  describe 'select_pinterest_board test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for select_snapchat_profile
  # Select Snapchat profile
  # Complete the Snapchat connection flow. Save the selected Public Profile and complete the account connection. Snapchat requires a Public Profile to publish Stories, Saved Stories, and Spotlight content. After Snapchat OAuth with headless&#x3D;true, you&#39;ll be redirected with tempToken, userProfile, publicProfiles, connect_token, platform&#x3D;snapchat, and step&#x3D;select_public_profile in the URL. Parse publicProfiles to build your custom selector UI, then call this endpoint with the selected profile. Use the X-Connect-Token header if you initiated the connection via API key. 
  # @param select_snapchat_profile_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_connect_token Short-lived connect token from the OAuth redirect (for API users)
  # @return [SelectSnapchatProfile200Response]
  describe 'select_snapchat_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_facebook_page
  # Update Facebook page
  # @param account_id 
  # @param update_facebook_page_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateFacebookPage200Response]
  describe 'update_facebook_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_gmb_location
  # Update GBP location
  # @param account_id 
  # @param update_gmb_location_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateGmbLocation200Response]
  describe 'update_gmb_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_linked_in_organization
  # Switch LinkedIn account type
  # @param account_id 
  # @param update_linked_in_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'update_linked_in_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_pinterest_boards
  # Set default Pinterest board
  # @param account_id 
  # @param update_pinterest_boards_request 
  # @param [Hash] opts the optional parameters
  # @return [ConnectBlueskyCredentials200Response]
  describe 'update_pinterest_boards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_reddit_subreddits
  # Set default subreddit
  # @param account_id 
  # @param update_reddit_subreddits_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateRedditSubreddits200Response]
  describe 'update_reddit_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
