=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::GMBReviewsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GMBReviewsApi' do
  before do
    # run before each test
    @api_instance = Late::GMBReviewsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GMBReviewsApi' do
    it 'should create an instance of GMBReviewsApi' do
      expect(@api_instance).to be_instance_of(Late::GMBReviewsApi)
    end
  end

  # unit tests for get_google_business_reviews
  # Get reviews
  # Fetches reviews for a connected Google Business Profile account.  Returns all reviews for the business location, including: - Reviewer information (name, profile photo) - Star rating (1-5) - Review comment/text - Business owner&#39;s reply (if any) - Review timestamps  Use pagination via &#x60;nextPageToken&#x60; to fetch all reviews for locations with many reviews. 
  # @param account_id The Late account ID (from /v1/accounts)
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Number of reviews to fetch per page (max 50)
  # @option opts [String] :page_token Pagination token from previous response
  # @return [GetGoogleBusinessReviews200Response]
  describe 'get_google_business_reviews test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
