=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::GMBPlaceActionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GMBPlaceActionsApi' do
  before do
    # run before each test
    @api_instance = Late::GMBPlaceActionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GMBPlaceActionsApi' do
    it 'should create an instance of GMBPlaceActionsApi' do
      expect(@api_instance).to be_instance_of(Late::GMBPlaceActionsApi)
    end
  end

  # unit tests for create_google_business_place_action
  # Create action link
  # Creates a place action link for a location.  Available action types: - &#x60;APPOINTMENT&#x60; - Booking an appointment - &#x60;ONLINE_APPOINTMENT&#x60; - Booking an online appointment - &#x60;DINING_RESERVATION&#x60; - Making a dining reservation (OpenTable, Resy, etc.) - &#x60;FOOD_ORDERING&#x60; - Ordering food for delivery and/or takeout (DoorDash, Uber Eats, etc.) - &#x60;FOOD_DELIVERY&#x60; - Ordering food for delivery only - &#x60;FOOD_TAKEOUT&#x60; - Ordering food for takeout only - &#x60;SHOP_ONLINE&#x60; - Shopping with delivery and/or pickup 
  # @param account_id 
  # @param create_google_business_place_action_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateGoogleBusinessPlaceAction200Response]
  describe 'create_google_business_place_action test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_google_business_place_action
  # Delete action link
  # @param account_id 
  # @param name The resource name of the place action link (e.g. locations/123/placeActionLinks/456)
  # @param [Hash] opts the optional parameters
  # @return [DeleteGoogleBusinessPlaceAction200Response]
  describe 'delete_google_business_place_action test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_google_business_place_actions
  # List action links
  # Lists place action links for a Google Business Profile location.  Place actions are the booking, ordering, and reservation buttons that appear on your listing. 
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size 
  # @option opts [String] :page_token 
  # @return [ListGoogleBusinessPlaceActions200Response]
  describe 'list_google_business_place_actions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
