=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::GMBLocationDetailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GMBLocationDetailsApi' do
  before do
    # run before each test
    @api_instance = Late::GMBLocationDetailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GMBLocationDetailsApi' do
    it 'should create an instance of GMBLocationDetailsApi' do
      expect(@api_instance).to be_instance_of(Late::GMBLocationDetailsApi)
    end
  end

  # unit tests for get_google_business_location_details
  # Get location details
  # Fetches detailed location information including opening hours, special hours, business description, phone numbers, website, categories, and more.  Use the &#x60;readMask&#x60; query parameter to request specific fields. 
  # @param account_id The Late account ID (from /v1/accounts)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :read_mask Comma-separated fields to return. Defaults to common fields. Available: name, title, phoneNumbers, categories, storefrontAddress, websiteUri, regularHours, specialHours, serviceArea, profile, openInfo, metadata, moreHours 
  # @return [GetGoogleBusinessLocationDetails200Response]
  describe 'get_google_business_location_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_google_business_location_details
  # Update location details
  # Updates location details such as opening hours, special hours, business description, phone, and website.  The &#x60;updateMask&#x60; field is required and specifies which fields to update.  Common update masks: - &#x60;regularHours&#x60; - Update opening hours - &#x60;specialHours&#x60; - Update holiday/special hours - &#x60;profile.description&#x60; - Update business description - &#x60;websiteUri&#x60; - Update website URL - &#x60;phoneNumbers&#x60; - Update phone numbers - &#x60;regularHours,specialHours&#x60; - Update both at once 
  # @param account_id The Late account ID (from /v1/accounts)
  # @param update_google_business_location_details_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateGoogleBusinessLocationDetails200Response]
  describe 'update_google_business_location_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
