=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::GMBFoodMenusApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GMBFoodMenusApi' do
  before do
    # run before each test
    @api_instance = Late::GMBFoodMenusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GMBFoodMenusApi' do
    it 'should create an instance of GMBFoodMenusApi' do
      expect(@api_instance).to be_instance_of(Late::GMBFoodMenusApi)
    end
  end

  # unit tests for get_google_business_food_menus
  # Get Google Business Profile food menus
  # Fetches food menus for a connected Google Business Profile location.  Returns the full menu structure including: - Menu names and descriptions - Sections (e.g. Appetizers, Entrees, Drinks) - Items with labels, pricing, dietary info, and allergens - Item options/variants  Only available for locations with food menu support (restaurants, cafes, etc.). 
  # @param account_id The Late account ID (from /v1/accounts)
  # @param [Hash] opts the optional parameters
  # @return [GetGoogleBusinessFoodMenus200Response]
  describe 'get_google_business_food_menus test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_google_business_food_menus
  # Update Google Business Profile food menus
  # Updates the food menus for a connected Google Business Profile location.  Send the full menus array. Use &#x60;updateMask&#x60; for partial updates (e.g. &#x60;\&quot;menus\&quot;&#x60; to only update the menus field).  Each menu can contain sections, and each section can contain items with pricing, dietary restrictions, allergens, and more. 
  # @param account_id The Late account ID (from /v1/accounts)
  # @param update_google_business_food_menus_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateGoogleBusinessFoodMenus200Response]
  describe 'update_google_business_food_menus test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
