=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::GMBMediaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GMBMediaApi' do
  before do
    # run before each test
    @api_instance = Late::GMBMediaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GMBMediaApi' do
    it 'should create an instance of GMBMediaApi' do
      expect(@api_instance).to be_instance_of(Late::GMBMediaApi)
    end
  end

  # unit tests for create_google_business_media
  # Upload photo
  # Creates a media item (photo) for a location from a publicly accessible URL.  Categories determine where the photo appears: - &#x60;COVER&#x60; - Cover photo - &#x60;PROFILE&#x60; - Profile photo - &#x60;LOGO&#x60; - Business logo - &#x60;EXTERIOR&#x60; - Exterior shots - &#x60;INTERIOR&#x60; - Interior shots - &#x60;FOOD_AND_DRINK&#x60; - Food and drink photos - &#x60;MENU&#x60; - Menu photos - &#x60;PRODUCT&#x60; - Product photos - &#x60;TEAMS&#x60; - Team/staff photos - &#x60;ADDITIONAL&#x60; - Other photos 
  # @param account_id 
  # @param create_google_business_media_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateGoogleBusinessMedia200Response]
  describe 'create_google_business_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_google_business_media
  # Delete photo
  # @param account_id 
  # @param media_id The media item ID to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteGoogleBusinessMedia200Response]
  describe 'delete_google_business_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_google_business_media
  # List media
  # Lists media items (photos) for a Google Business Profile location. Returns photo URLs, descriptions, categories, and metadata. 
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Number of items to return (max 100)
  # @option opts [String] :page_token Pagination token from previous response
  # @return [ListGoogleBusinessMedia200Response]
  describe 'list_google_business_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
