=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::LinkedInMentionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkedInMentionsApi' do
  before do
    # run before each test
    @api_instance = Late::LinkedInMentionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkedInMentionsApi' do
    it 'should create an instance of LinkedInMentionsApi' do
      expect(@api_instance).to be_instance_of(Late::LinkedInMentionsApi)
    end
  end

  # unit tests for get_linked_in_mentions
  # Resolve a LinkedIn profile or company URL to a URN for @mentions
  # Converts a LinkedIn profile URL (person) or company page URL (organization) to a URN that can be used to @mention them in posts.  **Supports both:** - **Person mentions:** &#x60;linkedin.com/in/username&#x60; or just &#x60;username&#x60; - **Organization mentions:** &#x60;linkedin.com/company/company-name&#x60; or &#x60;company/company-name&#x60;  **⚠️ Organization Admin Required for Person Mentions Only:** Person mentions require the connected LinkedIn account to have admin access to at least one LinkedIn Organization (Company Page). Organization mentions do NOT have this requirement - any LinkedIn account can tag companies.  **IMPORTANT - Display Name Requirement:** For **person mentions** to be clickable, the display name must **exactly match** what appears on their LinkedIn profile. - Organization mentions automatically retrieve the company name from LinkedIn API - Person mentions require the exact name, so provide the &#x60;displayName&#x60; parameter  **Mention Format:** Use the returned &#x60;mentionFormat&#x60; value directly in your post content: &#x60;&#x60;&#x60; Great insights from @[Miquel Palet](urn:li:person:4qj5ox-agD) on this topic! Excited to partner with @[Microsoft](urn:li:organization:1035)! &#x60;&#x60;&#x60; 
  # @param account_id The LinkedIn account ID
  # @param url LinkedIn profile URL, company URL, or vanity name. - Person: &#x60;miquelpalet&#x60;, &#x60;linkedin.com/in/miquelpalet&#x60; - Organization: &#x60;company/microsoft&#x60;, &#x60;linkedin.com/company/microsoft&#x60; 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :display_name The exact display name as shown on LinkedIn. - **Person mentions:** Required for clickable mentions. If not provided, a name is derived from the vanity URL which may not match exactly. - **Organization mentions:** Optional. If not provided, the company name is automatically retrieved from LinkedIn. 
  # @return [GetLinkedInMentions200Response]
  describe 'get_linked_in_mentions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
