=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::LinkedInMentionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkedInMentionsApi' do
  before do
    # run before each test
    @api_instance = Late::LinkedInMentionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkedInMentionsApi' do
    it 'should create an instance of LinkedInMentionsApi' do
      expect(@api_instance).to be_instance_of(Late::LinkedInMentionsApi)
    end
  end

  # unit tests for get_linked_in_mentions
  # Resolve LinkedIn mention
  # Converts a LinkedIn profile or company URL to a URN for @mentions in posts. Supports person mentions (&#x60;linkedin.com/in/username&#x60; or just &#x60;username&#x60;) and organization mentions (&#x60;linkedin.com/company/name&#x60; or &#x60;company/name&#x60;).  Person mentions require the connected account to have admin access to at least one LinkedIn Organization. Organization mentions work with any account.  For person mentions to be clickable, provide the &#x60;displayName&#x60; parameter matching the exact name on their LinkedIn profile. Organization names are fetched automatically.  Use the returned &#x60;mentionFormat&#x60; value directly in your post content. 
  # @param account_id The LinkedIn account ID
  # @param url LinkedIn profile URL, company URL, or vanity name. - Person: &#x60;miquelpalet&#x60;, &#x60;linkedin.com/in/miquelpalet&#x60; - Organization: &#x60;company/microsoft&#x60;, &#x60;linkedin.com/company/microsoft&#x60; 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :display_name The exact display name as shown on LinkedIn. - **Person mentions:** Required for clickable mentions. If not provided, a name is derived from the vanity URL which may not match exactly. - **Organization mentions:** Optional. If not provided, the company name is automatically retrieved from LinkedIn. 
  # @return [GetLinkedInMentions200Response]
  describe 'get_linked_in_mentions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
