=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::MediaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MediaApi' do
  before do
    # run before each test
    @api_instance = Late::MediaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MediaApi' do
    it 'should create an instance of MediaApi' do
      expect(@api_instance).to be_instance_of(Late::MediaApi)
    end
  end

  # unit tests for get_media_presigned_url
  # Get a presigned URL for direct file upload (up to 5GB)
  # Get a presigned URL to upload files directly to cloud storage. This is the recommended method for uploading files of any size, especially files larger than ~4MB.  **How it works:** 1. Call this endpoint with the filename and content type 2. Receive an &#x60;uploadUrl&#x60; (presigned) and &#x60;publicUrl&#x60; 3. PUT your file directly to the &#x60;uploadUrl&#x60; 4. Use the &#x60;publicUrl&#x60; in your posts  **Benefits:** - Supports files up to 5GB - Files upload directly to storage (faster, no server bottleneck) - No 413 errors from server body size limits  **Example:** &#x60;&#x60;&#x60;javascript // Step 1: Get presigned URL const response &#x3D; await fetch(&#39;https://getlate.dev/api/v1/media/presign&#39;, {   method: &#39;POST&#39;,   headers: {     &#39;Authorization&#39;: &#39;Bearer YOUR_API_KEY&#39;,     &#39;Content-Type&#39;: &#39;application/json&#39;   },   body: JSON.stringify({     filename: &#39;my-video.mp4&#39;,     contentType: &#39;video/mp4&#39;   }) }); const { uploadUrl, publicUrl } &#x3D; await response.json();  // Step 2: Upload file directly to storage await fetch(uploadUrl, {   method: &#39;PUT&#39;,   body: file,   headers: { &#39;Content-Type&#39;: &#39;video/mp4&#39; } });  // Step 3: Use publicUrl when creating your post // The publicUrl is ready to use immediately after upload completes &#x60;&#x60;&#x60; 
  # @param get_media_presigned_url_request 
  # @param [Hash] opts the optional parameters
  # @return [GetMediaPresignedUrl200Response]
  describe 'get_media_presigned_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
