=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::MessagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessagesApi' do
  before do
    # run before each test
    @api_instance = Late::MessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagesApi' do
    it 'should create an instance of MessagesApi' do
      expect(@api_instance).to be_instance_of(Late::MessagesApi)
    end
  end

  # unit tests for edit_inbox_message
  # Edit a message (Telegram only)
  # Edit the text and/or reply markup of a previously sent Telegram message. Only supported for Telegram. Returns 400 for other platforms. 
  # @param conversation_id The conversation ID
  # @param message_id The Telegram message ID to edit
  # @param edit_inbox_message_request 
  # @param [Hash] opts the optional parameters
  # @return [EditInboxMessage200Response]
  describe 'edit_inbox_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_inbox_conversation
  # Get conversation details
  # Retrieve details and metadata for a specific conversation. Requires accountId query parameter.
  # @param conversation_id The conversation ID (id field from list conversations endpoint). This is the platform-specific conversation identifier, not an internal database ID.
  # @param account_id The social account ID
  # @param [Hash] opts the optional parameters
  # @return [GetInboxConversation200Response]
  describe 'get_inbox_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_inbox_conversation_messages
  # Get messages in a conversation
  # Fetch messages for a specific conversation. Requires accountId query parameter.
  # @param conversation_id The conversation ID (id field from list conversations endpoint). This is the platform-specific conversation identifier, not an internal database ID.
  # @param account_id Social account ID
  # @param [Hash] opts the optional parameters
  # @return [GetInboxConversationMessages200Response]
  describe 'get_inbox_conversation_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_inbox_conversations
  # List conversations across all accounts
  # Fetch conversations (DMs) from all connected messaging accounts in a single API call. Supports filtering by profile and platform. Results are aggregated and deduplicated.  **Supported platforms:** Facebook, Instagram, Twitter/X, Bluesky, Reddit, Telegram 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :profile_id Filter by profile ID
  # @option opts [String] :platform Filter by platform
  # @option opts [String] :status Filter by conversation status
  # @option opts [String] :sort_order Sort order by updated time
  # @option opts [Integer] :limit Maximum number of conversations to return
  # @option opts [String] :cursor Pagination cursor for next page
  # @option opts [String] :account_id Filter by specific social account ID
  # @return [ListInboxConversations200Response]
  describe 'list_inbox_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_inbox_message
  # Send a message
  # Send a message in a conversation. Supports text, attachments, quick replies, buttons, carousels, and message tags.  **Attachment support by platform:** - Telegram: Images, videos, documents (up to 50MB) - Facebook Messenger: Images, videos, audio, files - Instagram: Images, videos, audio via URL (8MB images, 25MB video/audio) - Twitter/X: Images, videos (requires media upload) - Bluesky: Not supported - Reddit: Not supported  **Interactive message support:** | Field | Instagram | Facebook | Telegram | |---|---|---|---| | quickReplies | Meta quick_replies (13 max) | Meta quick_replies (13 max) | ReplyKeyboardMarkup (one_time) | | buttons | Generic template | Generic template | Inline keyboard | | template | Generic template (carousel) | Generic template (carousel) | Ignored | | replyMarkup | Ignored | Ignored | InlineKeyboardMarkup / ReplyKeyboardMarkup | | messagingType | Ignored | RESPONSE / UPDATE / MESSAGE_TAG | Ignored | | messageTag | HUMAN_AGENT only | 4 tag types | Ignored | | replyTo | Ignored | Ignored | reply_parameters |  Platform-specific fields are silently ignored on unsupported platforms. 
  # @param conversation_id The conversation ID (id field from list conversations endpoint). This is the platform-specific conversation identifier, not an internal database ID.
  # @param send_inbox_message_request 
  # @param [Hash] opts the optional parameters
  # @return [SendInboxMessage200Response]
  describe 'send_inbox_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_inbox_conversation
  # Update conversation status
  # Archive or activate a conversation. Requires accountId in request body.
  # @param conversation_id The conversation ID (id field from list conversations endpoint). This is the platform-specific conversation identifier, not an internal database ID.
  # @param update_inbox_conversation_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateInboxConversation200Response]
  describe 'update_inbox_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
