=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::PostsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostsApi' do
  before do
    # run before each test
    @api_instance = Late::PostsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostsApi' do
    it 'should create an instance of PostsApi' do
      expect(@api_instance).to be_instance_of(Late::PostsApi)
    end
  end

  # unit tests for bulk_upload_posts
  # Bulk upload from CSV
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :dry_run 
  # @option opts [File] :file 
  # @return [BulkUploadPosts200Response]
  describe 'bulk_upload_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_post
  # Create post
  # Immediate posts (publishNow: true) include platformPostUrl in the response. Scheduled posts: fetch via GET /v1/posts/{postId} after publish time. content is optional when media is attached, all platforms have customContent, or posting to YouTube only. Text-only posts require content. Stories ignore captions. Platform constraints: YouTube requires video. Instagram/TikTok require media (TikTok cannot mix videos and images). Instagram carousels up to 10 items, Threads up to 10 images. Facebook Stories need single image/video with contentType story. LinkedIn up to 20 images or single PDF. Pinterest single image/video with boardId. Bluesky up to 4 images. Snapchat single image/video. 
  # @param create_post_request 
  # @param [Hash] opts the optional parameters
  # @return [PostCreateResponse]
  describe 'create_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_post
  # Delete post
  # Delete a draft or scheduled post from Late. Only posts that have not been published can be deleted. To remove a published post from a social media platform, use the [Unpublish endpoint](#tag/Posts/operation/unpublishPost) instead. When deleting a scheduled or draft post that consumed upload quota, the quota will be automatically refunded. 
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [PostDeleteResponse]
  describe 'delete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_post
  # Get post
  # Fetch a single post by ID. For published posts, this returns platformPostUrl for each platform. 
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [PostGetResponse]
  describe 'get_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_posts
  # List posts
  # For published posts, each platform entry includes platformPostUrl with the public URL. Use status&#x3D;published to fetch only published posts with their URLs.  Platform notes: YouTube posts always include at least one video. Instagram/TikTok posts always include media (drafts may omit media). TikTok does not mix photos and videos in the same post. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (1-based)
  # @option opts [Integer] :limit Page size
  # @option opts [String] :status 
  # @option opts [String] :platform 
  # @option opts [String] :profile_id 
  # @option opts [String] :created_by 
  # @option opts [Date] :date_from 
  # @option opts [Date] :date_to 
  # @option opts [Boolean] :include_hidden 
  # @return [PostsListResponse]
  describe 'list_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retry_post
  # Retry failed post
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [PostRetryResponse]
  describe 'retry_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unpublish_post
  # Unpublish post
  # Deletes a published post from the specified platform. The post record in Late is kept but its platform status is updated to cancelled. Supported: Threads, Facebook, Twitter/X, LinkedIn, YouTube, Pinterest, Reddit, Bluesky, Google Business, Telegram. Not supported: Instagram, TikTok, Snapchat (must be deleted manually). Threaded posts (Twitter, Threads, Bluesky) delete all items in the thread. Telegram messages older than 48h may fail to delete. YouTube deletion is permanent. 
  # @param post_id 
  # @param unpublish_post_request 
  # @param [Hash] opts the optional parameters
  # @return [UnpublishPost200Response]
  describe 'unpublish_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_post
  # Update post
  # Update an existing post. Only draft, scheduled, failed, and partial posts can be edited. Published, publishing, and cancelled posts cannot be modified. 
  # @param post_id 
  # @param update_post_request 
  # @param [Hash] opts the optional parameters
  # @return [PostUpdateResponse]
  describe 'update_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
