=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::QueueApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'QueueApi' do
  before do
    # run before each test
    @api_instance = Late::QueueApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QueueApi' do
    it 'should create an instance of QueueApi' do
      expect(@api_instance).to be_instance_of(Late::QueueApi)
    end
  end

  # unit tests for create_queue_slot
  # Create a new queue for a profile
  # Create an additional queue for a profile. The first queue created becomes the default. Subsequent queues are non-default unless explicitly set. 
  # @param create_queue_slot_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateQueueSlot201Response]
  describe 'create_queue_slot test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_queue_slot
  # Delete a queue schedule
  # Delete a queue from a profile. Requires queueId to specify which queue to delete. If deleting the default queue, another queue will be promoted to default. 
  # @param profile_id 
  # @param queue_id Queue ID to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteQueueSlot200Response]
  describe 'delete_queue_slot test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_next_queue_slot
  # Preview the next available queue slot (informational only)
  # Returns the next available queue slot for preview/informational purposes.  **Important: To schedule a post to the queue, do NOT use this endpoint&#39;s response with &#x60;scheduledFor&#x60;.** That creates a manual post, not a queue post.  Instead, use &#x60;POST /v1/posts&#x60; with &#x60;queuedFromProfile&#x60; (and optionally &#x60;queueId&#x60;). The system will automatically assign the next available slot with proper locking to prevent race conditions.  This endpoint is useful for: - Showing users when their next post will go out before they commit - Debugging/verifying queue configuration - Building UI previews  If no queueId is specified, uses the profile&#39;s default queue. 
  # @param profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :queue_id Specific queue ID (optional, defaults to profile&#39;s default queue)
  # @return [GetNextQueueSlot200Response]
  describe 'get_next_queue_slot test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_queue_slots
  # Get queue schedules for a profile
  # Retrieve queue schedules for a profile. Each profile can have multiple queues. - Without &#x60;all&#x3D;true&#x60;: Returns the default queue (or specific queue if queueId provided) - With &#x60;all&#x3D;true&#x60;: Returns all queues for the profile 
  # @param profile_id Profile ID to get queues for
  # @param [Hash] opts the optional parameters
  # @option opts [String] :queue_id Specific queue ID to retrieve (optional)
  # @option opts [String] :all Set to &#39;true&#39; to list all queues for the profile
  # @return [ListQueueSlots200Response]
  describe 'list_queue_slots test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for preview_queue
  # Preview upcoming queue slots for a profile
  # @param profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count 
  # @return [PreviewQueue200Response]
  describe 'preview_queue test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_queue_slot
  # Create or update a queue schedule
  # Create a new queue or update an existing one. - Without queueId: Creates or updates the default queue - With queueId: Updates the specific queue - With setAsDefault&#x3D;true: Makes this queue the default for the profile 
  # @param update_queue_slot_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateQueueSlot200Response]
  describe 'update_queue_slot test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
