=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::RedditSearchApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RedditSearchApi' do
  before do
    # run before each test
    @api_instance = Late::RedditSearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedditSearchApi' do
    it 'should create an instance of RedditSearchApi' do
      expect(@api_instance).to be_instance_of(Late::RedditSearchApi)
    end
  end

  # unit tests for get_reddit_feed
  # Fetch subreddit feed via a connected account
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :subreddit 
  # @option opts [String] :sort 
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @option opts [String] :t 
  # @return [GetRedditFeed200Response]
  describe 'get_reddit_feed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_reddit
  # Search Reddit posts via a connected account
  # @param account_id 
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :subreddit 
  # @option opts [String] :restrict_sr 
  # @option opts [String] :sort 
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [SearchReddit200Response]
  describe 'search_reddit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
