=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = Late::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(Late::UsersApi)
    end
  end

  # unit tests for get_user
  # Get user by id (self or invited)
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [GetUser200Response]
  describe 'get_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users
  # List team users (root + invited)
  # @param [Hash] opts the optional parameters
  # @return [ListUsers200Response]
  describe 'list_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
