=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Late::ApproveWhatsAppGroupJoinRequestsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Late::ApproveWhatsAppGroupJoinRequestsRequest do
  #let(:instance) { Late::ApproveWhatsAppGroupJoinRequestsRequest.new }

  describe 'test an instance of ApproveWhatsAppGroupJoinRequestsRequest' do
    it 'should create an instance of ApproveWhatsAppGroupJoinRequestsRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Late::ApproveWhatsAppGroupJoinRequestsRequest)
    end
  end

  describe 'test attribute "phone_numbers"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
