=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Late::GetPostReactions200ResponseReactionsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Late::GetPostReactions200ResponseReactionsInner do
  #let(:instance) { Late::GetPostReactions200ResponseReactionsInner.new }

  describe 'test an instance of GetPostReactions200ResponseReactionsInner' do
    it 'should create an instance of GetPostReactions200ResponseReactionsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Late::GetPostReactions200ResponseReactionsInner)
    end
  end

  describe 'test attribute "reaction_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reaction_label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reacted_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
