=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Late::GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Late::GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner do
  #let(:instance) { Late::GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.new }

  describe 'test an instance of GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner' do
    it 'should create an instance of GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Late::GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner)
    end
  end

  describe 'test attribute "start_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "open_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "close_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "closed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
