=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Late::PlatformAnalytics
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Late::PlatformAnalytics do
  #let(:instance) { Late::PlatformAnalytics.new }

  describe 'test an instance of PlatformAnalytics' do
    it 'should create an instance of PlatformAnalytics' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Late::PlatformAnalytics)
    end
  end

  describe 'test attribute "platform"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "account_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "account_username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "analytics"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "account_metrics"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
