=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1
Contact: support@getlate.dev
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Late::UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Late::UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel do
  #let(:instance) { Late::UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel.new }

  describe 'test an instance of UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel' do
    it 'should create an instance of UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Late::UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerFreeFormServiceItemLabel)
    end
  end

  describe 'test attribute "display_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "language_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
