=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Late
  # Constraints: - Feed posts require images with aspect ratio between 0.8 (4:5 portrait) and 1.91 (1.91:1 landscape). - Images outside this range (e.g., 9:16 Stories/TikTok format) must use contentType 'story'. - Validation happens at post creation; invalid images are rejected immediately with helpful error messages. - Carousels support up to 10 media items. - Stories require media; no captions are published with Stories. - User tags: coordinates range from 0.0 to 1.0 representing position from top-left corner. Tagged users receive notifications.  **Automatic Compression (similar to Bluesky):** - All images (story, post, carousel, thumbnails) exceeding 8 MB are automatically compressed using quality reduction and resizing. - Story videos exceeding 100 MB are automatically compressed. - Reel videos exceeding 300 MB are automatically compressed. - Compression uses Sharp (images) and FFmpeg (videos) to maintain quality while meeting size limits. - Original files are preserved; compressed versions are uploaded to blob storage automatically. 
  class InstagramPlatformData < ApiModelBase
    # Set to 'story' to publish as a Story. Default posts become Reels or feed depending on media.
    attr_accessor :content_type

    # For Reels only. When true (default), the Reel appears on both the Reels tab and your main profile feed. Set to false to post to the Reels tab only.
    attr_accessor :share_to_feed

    # Up to 3 Instagram usernames to invite as collaborators (feed/Reels only)
    attr_accessor :collaborators

    # Optional first comment to add after the post is created (not applied to Stories)
    attr_accessor :first_comment

    attr_accessor :trial_params

    # Tag Instagram users in photos by username and position coordinates. Only works for single image posts and the first image of carousel posts. Not supported for stories or videos.
    attr_accessor :user_tags

    # Custom name for the original audio in Reels. Replaces the default \"Original Audio\" label. Only applies to Reels (video posts). Can only be set once - either during creation or later from the Instagram audio page in the app. 
    attr_accessor :audio_name

    # Millisecond offset from the start of the video to use as the Reel thumbnail. Only applies to Reels (video posts). If a custom thumbnail URL (instagramThumbnail in mediaItems) is provided, it takes priority and this offset is ignored. Defaults to 0 (first frame). 
    attr_accessor :thumb_offset

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'content_type' => :'contentType',
        :'share_to_feed' => :'shareToFeed',
        :'collaborators' => :'collaborators',
        :'first_comment' => :'firstComment',
        :'trial_params' => :'trialParams',
        :'user_tags' => :'userTags',
        :'audio_name' => :'audioName',
        :'thumb_offset' => :'thumbOffset'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'content_type' => :'String',
        :'share_to_feed' => :'Boolean',
        :'collaborators' => :'Array<String>',
        :'first_comment' => :'String',
        :'trial_params' => :'InstagramPlatformDataTrialParams',
        :'user_tags' => :'Array<InstagramPlatformDataUserTagsInner>',
        :'audio_name' => :'String',
        :'thumb_offset' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Late::InstagramPlatformData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Late::InstagramPlatformData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'share_to_feed')
        self.share_to_feed = attributes[:'share_to_feed']
      else
        self.share_to_feed = true
      end

      if attributes.key?(:'collaborators')
        if (value = attributes[:'collaborators']).is_a?(Array)
          self.collaborators = value
        end
      end

      if attributes.key?(:'first_comment')
        self.first_comment = attributes[:'first_comment']
      end

      if attributes.key?(:'trial_params')
        self.trial_params = attributes[:'trial_params']
      end

      if attributes.key?(:'user_tags')
        if (value = attributes[:'user_tags']).is_a?(Array)
          self.user_tags = value
        end
      end

      if attributes.key?(:'audio_name')
        self.audio_name = attributes[:'audio_name']
      end

      if attributes.key?(:'thumb_offset')
        self.thumb_offset = attributes[:'thumb_offset']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@thumb_offset.nil? && @thumb_offset < 0
        invalid_properties.push('invalid value for "thumb_offset", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      content_type_validator = EnumAttributeValidator.new('String', ["story"])
      return false unless content_type_validator.valid?(@content_type)
      return false if !@thumb_offset.nil? && @thumb_offset < 0
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] content_type Object to be assigned
    def content_type=(content_type)
      validator = EnumAttributeValidator.new('String', ["story"])
      unless validator.valid?(content_type)
        fail ArgumentError, "invalid value for \"content_type\", must be one of #{validator.allowable_values}."
      end
      @content_type = content_type
    end

    # Custom attribute writer method with validation
    # @param [Object] thumb_offset Value to be assigned
    def thumb_offset=(thumb_offset)
      if thumb_offset.nil?
        fail ArgumentError, 'thumb_offset cannot be nil'
      end

      if thumb_offset < 0
        fail ArgumentError, 'invalid value for "thumb_offset", must be greater than or equal to 0.'
      end

      @thumb_offset = thumb_offset
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          content_type == o.content_type &&
          share_to_feed == o.share_to_feed &&
          collaborators == o.collaborators &&
          first_comment == o.first_comment &&
          trial_params == o.trial_params &&
          user_tags == o.user_tags &&
          audio_name == o.audio_name &&
          thumb_offset == o.thumb_offset
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [content_type, share_to_feed, collaborators, first_comment, trial_params, user_tags, audio_name, thumb_offset].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
