=begin
#Late API

#API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Late
  # Media referenced in posts. URLs must be publicly reachable over HTTPS by the destination platforms. When using third‑party storage, ensure signed links remain valid until upload completes.  **Uploading Media:** Use `POST /v1/media/presign` to get a presigned URL, then upload your file directly to cloud storage. Supports files up to 5GB. See the `/v1/media/presign` endpoint documentation for details.  **Automatic Media Compression:** Late automatically compresses media that exceeds platform limits, so you don't need to worry about file size restrictions. Compression happens server-side during publishing.  **Image compression by platform:** - Twitter/X: >5 MB - Instagram: >8 MB - Threads: >8 MB - Facebook: >10 MB - LinkedIn: >8 MB - TikTok: >20 MB - Pinterest: >32 MB - Reddit: >20 MB - Snapchat: >20 MB - Telegram: >10 MB - Bluesky: >1 MB - YouTube (thumbnails): >2 MB - Google Business: >5 MB  **Video compression by platform:** - Twitter/X: >512 MB - Instagram Stories: >100 MB - Instagram Reels: >300 MB - Facebook: >4 GB - LinkedIn: >5 GB - TikTok: >4 GB - Pinterest: >2 GB - Snapchat: >500 MB - Telegram: >50 MB  Note: Videos larger than 200 MB may not be compressed due to server timeout constraints. For best results, compress very large videos before uploading. 
  class MediaItem < ApiModelBase
    attr_accessor :type

    attr_accessor :url

    attr_accessor :filename

    # Optional file size in bytes
    attr_accessor :size

    # Optional MIME type (e.g. image/jpeg, video/mp4)
    attr_accessor :mime_type

    # Optional thumbnail image URL for videos
    attr_accessor :thumbnail

    # Optional custom cover image URL for Instagram Reels
    attr_accessor :instagram_thumbnail

    # Internal flag indicating the image was resized for TikTok
    attr_accessor :tiktok_processed

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'url' => :'url',
        :'filename' => :'filename',
        :'size' => :'size',
        :'mime_type' => :'mimeType',
        :'thumbnail' => :'thumbnail',
        :'instagram_thumbnail' => :'instagramThumbnail',
        :'tiktok_processed' => :'tiktokProcessed'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'url' => :'String',
        :'filename' => :'String',
        :'size' => :'Integer',
        :'mime_type' => :'String',
        :'thumbnail' => :'String',
        :'instagram_thumbnail' => :'String',
        :'tiktok_processed' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Late::MediaItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Late::MediaItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'mime_type')
        self.mime_type = attributes[:'mime_type']
      end

      if attributes.key?(:'thumbnail')
        self.thumbnail = attributes[:'thumbnail']
      end

      if attributes.key?(:'instagram_thumbnail')
        self.instagram_thumbnail = attributes[:'instagram_thumbnail']
      end

      if attributes.key?(:'tiktok_processed')
        self.tiktok_processed = attributes[:'tiktok_processed']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      type_validator = EnumAttributeValidator.new('String', ["image", "video", "gif", "document"])
      return false unless type_validator.valid?(@type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["image", "video", "gif", "document"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          url == o.url &&
          filename == o.filename &&
          size == o.size &&
          mime_type == o.mime_type &&
          thumbnail == o.thumbnail &&
          instagram_thumbnail == o.instagram_thumbnail &&
          tiktok_processed == o.tiktok_processed
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, url, filename, size, mime_type, thumbnail, instagram_thumbnail, tiktok_processed].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
